# SPDX-License-Identifier: GPL-3.0+

Import('env')

import os
import gzip
import shutil
from pathlib import Path, PurePosixPath
import glob
import subprocess
import json
import re
import time
import hashlib

def remove_comments_regex(text):
    text = re.sub(r'//.*', '', text)
    text = re.sub(r'/\*[\s\S]*?\*/', '', text)
    return text

def prepare_www_files(source, target, env):

    filetypes_to_gzip = ['js', 'html', 'css', 'map']
    ignore_suffix = []

    proj_dir = Path(env.get("PROJECT_DIR"))
    data_src_dir = os.path.join(proj_dir, 'src', 'data_src')
    tmp_dir = os.path.join(proj_dir, 'data_tmp')
    src_dir = os.path.join(proj_dir, 'src', 'src')
    dst_header_file = os.path.join(src_dir, "static_files.h")

    if(os.path.exists(tmp_dir)):
        print('  Delete temproary dir {}'.format(tmp_dir))
        shutil.rmtree(tmp_dir)

    print('  Re-creating empty temporary dir {} '.format(tmp_dir))
    os.mkdir(tmp_dir)

    files_to_gzip = []
    for extension in filetypes_to_gzip:
        files_to_gzip.extend(glob.glob(os.path.join(data_src_dir, '*.' + extension)))

    print('  files to gzip: ' + str(files_to_gzip))

    all_files = glob.glob(os.path.join(data_src_dir, '*.*'))
    files_to_copy = list(set(all_files) - set(files_to_gzip))


    print('  files to copy: ' + str(files_to_copy))
    dst_files = []
    for file in files_to_copy:
        if PurePosixPath(file).suffix in ignore_suffix:
            continue

        print('  COPY: ' + file)
        dst = os.path.join(tmp_dir, os.path.basename(file))
        shutil.copy(file, dst)
        dst_files.append(dst)


    for file in files_to_gzip:
        dst = os.path.join(tmp_dir, os.path.basename(file) + '.gz')
        dst_files.append(dst)
        print('  GZIP: ' + file + ' -> ' + dst)
        cmd = 'gzip -9 < {S} > {D}'.format(S=file, D=dst)
        subprocess.check_call(cmd, shell=True)

    fcnt = 0;
    if os.path.exists(dst_header_file):
        print('  Delete existing destination: ' + dst_header_file)
        os.remove(dst_header_file)
    with open(dst_header_file, 'a') as fdst:
        print('  CREATE: ' + dst_header_file)
        fdst.write('#include <stdio.h>\n')

        h_file_content = []
        for file in dst_files:
            cnt = 0
            filename = os.path.basename(file)
            with open(file, 'rb') as fsrc:
                print('   PROCESS: ' + filename)
                fdst.write("/* %s */\nconst unsigned char file_%02d[] = {" % (filename, fcnt))
                while 1:
                    byte = fsrc.read(1)
                    if not byte:
                        break
                    if cnt > 0:
                        fdst.write(", ")
                    if cnt % 8 == 0:
                        fdst.write("\n    ")
                    cnt+=1
                    fdst.write("0x%02x" % ord(byte))
                fdst.write("\n};\n\n")

            gzip = 0
            filetype ="text/html"
            if filename.endswith('.gz'):
                filename = filename[0:-3]
                gzip = 1
            if filename.endswith('.css'):
                filetype = "text/css"
            if filename.endswith('.js'):
                filetype = "text/javascript"
            if filename.endswith('.ogg'):
                filetype = "audio/ogg"
            if filename.endswith('.svg'):
                filetype = "image/svg+xml"
            h_file_content.append((filename, gzip, filetype, "file_%02d" %fcnt, cnt))
            fcnt+=1

        fdst.write("""
struct static_files {
    const char *name;
    unsigned int is_gzip;
    const char *type;
    const unsigned char *data;
    size_t data_len;
};

const struct static_files STATIC_FILES[] = {
""")

        for hc in h_file_content:
            fdst.write('    {.name = %-30s .is_gzip = %d, .type = %-18s .data = %-7s, .data_len = %-5d },\n' %('"/' + hc[0]+'",', hc[1], '"'+hc[2]+'",', hc[3], hc[4]))
        fdst.write("    {.name = NULL, .data = NULL}\n};\n")

    # Cleanup
    if(os.path.exists(tmp_dir)):
        print('  Delete temproary dir {}'.format(tmp_dir))
        shutil.rmtree(tmp_dir)

def format_value(text):
    time_s = str(int(time.time()))
    text = re.sub(r'\{\{time}}', time_s , str(text))
    return text


def load_default_config(source, target, env):
    proj_dir = Path(env.get("PROJECT_DIR"))
    config_file = os.path.join(proj_dir, 'config.json')
    dst_file = os.path.join(proj_dir, 'src', 'src', 'config_default.c')
    config_data_h = os.path.join(proj_dir, 'src', 'src', 'config_data.h')
    default_cfg_json = {}
    config_magic = hashlib.md5(open(config_data_h,'rb').read()).hexdigest()[-8:]

    if os.path.isfile(config_file):
        with open(config_file, 'r') as f:
            content = remove_comments_regex(f.read())
            default_cfg_json = json.loads(content)
        config_magic = hashlib.md5(open(config_file,'rb').read()).hexdigest()[-8:]

    with open(dst_file, 'w') as fdst:
        fdst.write("/** AUTOGENERATED FILE FROM prepare_data_folder.py **/\n\n")
        fdst.write("#include \"config.h\"\n")
        fdst.write("#include \"config_default.h\"\n\n\n")

        fdst.write("const char* cfg_default_magic(){\n")
        fdst.write("  return \"{}\";\n".format(config_magic))
        fdst.write("}\n\n")

        fdst.write("void cfg_default_set(config_data_t *cfg){\n")

        for key, value in default_cfg_json.items():
            fdst.write('  cfg_data_set_param(cfg, "{}", "{}");\n'.format(key, format_value(value)))

        if not os.path.isfile(config_file):
            fdst.write('  /* no config.json */\n')

        fdst.write("}")


proj_dir = env.get("PROJECT_DIR")
env.AddCustomTarget(
    name="js_app",
    dependencies=None,
    actions=["cd {}/src/js && esbuild src/app.ts --bundle --outfile=../data_src/app.js --minify --target=esnext --sourcemap".format(proj_dir)],
    title="esbuild src/app.ts",
    description="esbuild src/app.ts",
    always_build=True,
)

env.AddCustomTarget(
    name="static_files_h",
    dependencies=["js_app"],
    actions=prepare_www_files,
    title="Generate Header",
    description="Generates a header file static_files.h",
    always_build=True,
)

env.AddCustomTarget(
    name="default_config_c",
    dependencies=["static_files_h"],
    actions=load_default_config,
    title="Create default config",
    description="Generates config_default.c",
    always_build=True,
)

# forward option --upload-port
up_port = env.get('UPLOAD_PORT')
if up_port is None:
    up_port = ""
else:
    up_port = "--upload-port {}".format(up_port)


env.AddCustomTarget(
    name="update_fw",
    dependencies=["default_config_c"],
    actions=["pio run -t upload {}".format(up_port)],
    title="Update firmware",
    description="Do what ever is needed and update the ESP32",
    always_build=False,
)

env.AddCustomTarget(
    name="js_server",
    dependencies=None,
    actions=["cd {}/src/js && esbuild src/ctrld.ts --bundle --outfile=../server/www/ctrld.js --minify --target=esnext --sourcemap".format(proj_dir)],
    title="esbuild src/ctrld.ts",
    description="esbuild src/ctrld.ts",
    always_build=True,
)

# Setup dependency tracking and auto-generation hooks
proj_dir_path = Path(proj_dir)
static_files_h = proj_dir_path / "src" / "src" / "static_files.h"
config_default_c = proj_dir_path / "src" / "src" / "config_default.c"
data_src_dir = proj_dir_path / "src" / "data_src"
js_src_dir = proj_dir_path / "src" / "js" / "src"
config_file = proj_dir_path / "config.json"
config_data_h = proj_dir_path / "src" / "src" / "config_data.h"

def generate_all_files(source, target, env):
    """
    Generate all required files (static_files.h and config_default.c).
    This must run before compilation starts so that C files see the latest headers.
    """
    print("=== Generating required build files ===")
    
    # Build JS app
    js_cmd = "cd {}/src/js && esbuild src/app.ts --bundle --outfile=../data_src/app.js --minify --target=esnext --sourcemap".format(proj_dir)
    print("Building JavaScript app...")
    try:
        subprocess.check_call(js_cmd, shell=True)
    except Exception as e:
        print(f"Warning: Failed to build JS app: {e}")
    
    # Generate static_files.h
    print("Generating static_files.h...")
    try:
        prepare_www_files(None, None, env)
    except Exception as e:
        print(f"Error: Failed to generate static_files.h: {e}")
        raise
    
    # Generate config_default.c
    print("Generating config_default.c...")
    try:
        load_default_config(None, None, env)
    except Exception as e:
        print(f"Error: Failed to generate config_default.c: {e}")
        raise
    
    print("=== Auto-generation complete ===")

# Always regenerate files at script load time to ensure they're current
# before compilation starts. PlatformIO's dependency tracking will then
# automatically recompile C files if the headers changed.
generate_all_files(None, None, env)

# Declare dependencies so PlatformIO knows the firmware depends on these files
env.Depends("$BUILD_DIR/${PROGNAME}.elf", [str(static_files_h), str(config_default_c)])
